// Code generated by contracts/scripts/generate.mjs; DO NOT EDIT.

package contracts

type SymmetryAdapterCapabilitiesV1 struct {
	Adapter            *Adapter `json:"adapter,omitempty"`
	Interactive        *bool    `json:"interactive,omitempty"`
	ProviderAccess     *bool    `json:"provider_access,omitempty"`
	StructuredInput    *bool    `json:"structured_input,omitempty"`
	SupervisoryControl *bool    `json:"supervisory_control,omitempty"`
}

type Adapter struct {
	ImplementationVersion string            `json:"implementation_version"`
	Kind                  string            `json:"kind"`
	NativeVersion         string            `json:"native_version"`
	Operations            AdapterOperations `json:"operations"`
	ProtocolVersion       int64             `json:"protocol_version"`
}

type AdapterOperations struct {
	ApprovalResponse bool      `json:"approval_response"`
	Cancel           bool      `json:"cancel"`
	Events           bool      `json:"events"`
	Guidance         Guidance  `json:"guidance"`
	Handoff          bool      `json:"handoff"`
	HardCostLimit    bool      `json:"hard_cost_limit"`
	Pause            PauseEnum `json:"pause"`
	Resume           bool      `json:"resume"`
	Start            bool      `json:"start"`
	Usage            Usage     `json:"usage"`
}

type SymmetryAdmissionV1 struct {
	AdmissionID        string                           `json:"admission_id"`
	ContextHash        string                           `json:"context_hash"`
	ContextSnapshotID  string                           `json:"context_snapshot_id"`
	GoalID             string                           `json:"goal_id"`
	GoalRevision       int64                            `json:"goal_revision"`
	HandoffSourceRunID *string                          `json:"handoff_source_run_id,omitempty"`
	Limits             Limits                           `json:"limits"`
	ModelProfile       string                           `json:"model_profile"`
	ProviderScope      interface{}                      `json:"provider_scope"`
	Purpose            SymmetryAdmissionV1Purpose       `json:"purpose"`
	RequestedSessionID *string                          `json:"requested_session_id"`
	SchemaVersion      SymmetryAdmissionV1SchemaVersion `json:"schema_version"`
	SessionMode        SessionMode                      `json:"session_mode"`
	Subject            SymmetryAdmissionV1Subject       `json:"subject"`
	ValidationOfTaskID interface{}                      `json:"validation_of_task_id"`
	WorkItemID         *string                          `json:"work_item_id"`
}

type Limits struct {
	DeadlineAt      string  `json:"deadline_at"`
	MaxCostMicrousd *string `json:"max_cost_microusd"`
	MaxTurns        int64   `json:"max_turns"`
}

type SymmetryAdmissionV1Subject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type SymmetryContextSnapshotV1 struct {
	AdvisoryRecall    []ContextSource                        `json:"advisory_recall"`
	ApprovedGoal      ApprovedGoal                           `json:"approved_goal"`
	ContentHash       string                                 `json:"content_hash"`
	CreatedAt         string                                 `json:"created_at"`
	CurrentDecisions  []DecisionReference                    `json:"current_decisions"`
	FailedAttempts    []FailedAttempt                        `json:"failed_attempts"`
	GoalID            string                                 `json:"goal_id"`
	GoalRevision      int64                                  `json:"goal_revision"`
	NextAction        *NextActionClass                       `json:"next_action"`
	SchemaVersion     SymmetryContextSnapshotV1SchemaVersion `json:"schema_version"`
	Size              ContextSize                            `json:"size"`
	SnapshotID        string                                 `json:"snapshot_id"`
	Sources           []ContextSource                        `json:"sources"`
	Subject           SymmetryContextSnapshotV1Subject       `json:"subject"`
	ValidatedEvidence []EvidenceReference                    `json:"validated_evidence"`
	WorkContract      WorkContract                           `json:"work_contract"`
	WorkItemID        *string                                `json:"work_item_id"`
}

type ContextSource struct {
	Content        Content `json:"content"`
	ContentHash    string  `json:"content_hash"`
	ObservedAt     string  `json:"observed_at"`
	Required       bool    `json:"required"`
	ResourceID     string  `json:"resource_id"`
	SourceKind     string  `json:"source_kind"`
	SourceRevision string  `json:"source_revision"`
	Stale          *bool   `json:"stale,omitempty"`
	Trust          Trust   `json:"trust"`
}

type Content struct {
	Kind  ContentKind `json:"kind"`
	Value string      `json:"value"`
}

type ApprovedGoal struct {
	AuthorityPolicy ApprovedGoalAuthorityPolicy `json:"authority_policy"`
	GoalID          string                      `json:"goal_id"`
	Objective       string                      `json:"objective"`
	Revision        int64                       `json:"revision"`
}

type ApprovedGoalAuthorityPolicy struct {
	AllowedActions                 []string `json:"allowed_actions"`
	OperatorRequiredForCompletion  bool     `json:"operator_required_for_completion"`
	OperatorRequiredForScopeChange bool     `json:"operator_required_for_scope_change"`
	PublicationAllowed             bool     `json:"publication_allowed"`
}

type DecisionReference struct {
	ActionHash string `json:"action_hash"`
	DecisionID string `json:"decision_id"`
	State      State  `json:"state"`
}

type FailedAttempt struct {
	ObservedAt string  `json:"observed_at"`
	Reason     string  `json:"reason"`
	RunID      *string `json:"run_id"`
	TaskID     string  `json:"task_id"`
}

type NextActionClass struct {
	Kind            NextActionKind     `json:"kind"`
	ProducingTaskID *string            `json:"producing_task_id,omitempty"`
	Reason          *string            `json:"reason,omitempty"`
	WorkItemID      *string            `json:"work_item_id,omitempty"`
	ExternalRef     *string            `json:"external_ref,omitempty"`
	ResourceID      *string            `json:"resource_id,omitempty"`
	Blocker         *NextActionBlocker `json:"blocker,omitempty"`
}

type NextActionBlocker struct {
	DecisionID  *string     `json:"decision_id,omitempty"`
	Kind        BlockerKind `json:"kind"`
	ExternalRef *string     `json:"external_ref,omitempty"`
	NextCheckAt *string     `json:"next_check_at,omitempty"`
	ResourceID  *string     `json:"resource_id,omitempty"`
	WorkItemIDS []string    `json:"work_item_ids,omitempty"`
	Code        *string     `json:"code,omitempty"`
	Detail      *string     `json:"detail,omitempty"`
}

type ContextSize struct {
	ByteBudget     int64  `json:"byte_budget"`
	MandatoryBytes int64  `json:"mandatory_bytes"`
	OptionalBytes  int64  `json:"optional_bytes"`
	TokenEstimate  *int64 `json:"token_estimate"`
	TotalBytes     int64  `json:"total_bytes"`
}

type SymmetryContextSnapshotV1Subject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type EvidenceReference struct {
	EvidenceID  string  `json:"evidence_id"`
	PredicateID string  `json:"predicate_id"`
	SubjectHash string  `json:"subject_hash"`
	Verdict     Verdict `json:"verdict"`
}

type WorkContract struct {
	Acceptance         WorkContractAcceptance    `json:"acceptance"`
	ChangeTarget       *WorkContractChangeTarget `json:"change_target"`
	Description        string                    `json:"description"`
	Purpose            WorkContractPurpose       `json:"purpose"`
	Title              string                    `json:"title"`
	ValidationBindings []ValidationBinding       `json:"validation_bindings"`
}

type WorkContractAcceptance struct {
	Description   string                  `json:"description"`
	Predicates    []PurplePredicate       `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type PurplePredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type WorkContractChangeTarget struct {
	Kind           ChangeTargetKind `json:"kind"`
	SourceBranch   *string          `json:"source_branch,omitempty"`
	TargetBranch   *string          `json:"target_branch,omitempty"`
	PullRequestURL *string          `json:"pull_request_url,omitempty"`
}

type ValidationBinding struct {
	AllowedRuntimeIDS []string              `json:"allowed_runtime_ids"`
	Kind              ValidationBindingKind `json:"kind"`
	ProfileDigest     string                `json:"profile_digest"`
	ProfileName       string                `json:"profile_name"`
}

type SymmetryDecisionV1 struct {
	ActionHash    string                          `json:"action_hash"`
	ActorRef      *string                         `json:"actor_ref"`
	CreatedAt     string                          `json:"created_at"`
	DecisionID    string                          `json:"decision_id"`
	ExpiresAt     *string                         `json:"expires_at"`
	GoalID        string                          `json:"goal_id"`
	GoalRevision  int64                           `json:"goal_revision"`
	Kind          SymmetryDecisionV1Kind          `json:"kind"`
	LockVersion   int64                           `json:"lock_version"`
	Options       []DecisionOption                `json:"options"`
	Question      string                          `json:"question"`
	Resolution    *DecisionResolution             `json:"resolution"`
	SchemaVersion SymmetryDecisionV1SchemaVersion `json:"schema_version"`
	State         State                           `json:"state"`
	SubjectHash   *string                         `json:"subject_hash"`
	UpdatedAt     string                          `json:"updated_at"`
	WorkItemID    *string                         `json:"work_item_id"`
}

type DecisionOption struct {
	Consequence string `json:"consequence"`
	ID          string `json:"id"`
	Label       string `json:"label"`
}

type DecisionResolution struct {
	ActorRef   *string `json:"actor_ref"`
	Comment    *string `json:"comment"`
	OptionID   string  `json:"option_id"`
	ResolvedAt string  `json:"resolved_at"`
}

type SymmetryEvidenceV1 struct {
	EvidenceID       string                          `json:"evidence_id"`
	EvidenceKey      string                          `json:"evidence_key"`
	Kind             SymmetryEvidenceV1Kind          `json:"kind"`
	ObservedAt       string                          `json:"observed_at"`
	Payload          Receipt                         `json:"payload"`
	RunID            string                          `json:"run_id"`
	SchemaVersion    SymmetryEvidenceV1SchemaVersion `json:"schema_version"`
	SourceRef        SourceRef                       `json:"source_ref"`
	SourceRevision   string                          `json:"source_revision"`
	Subject          SymmetryEvidenceV1Subject       `json:"subject"`
	SubjectHash      string                          `json:"subject_hash"`
	ValidatorProfile *string                         `json:"validator_profile"`
	Verdict          Verdict                         `json:"verdict"`
}

type Receipt struct {
	CommandArgvDigest *string                   `json:"command_argv_digest,omitempty"`
	ExitCode          *int64                    `json:"exit_code,omitempty"`
	FinishedAt        *string                   `json:"finished_at,omitempty"`
	OutputRef         *OutputRef                `json:"output_ref,omitempty"`
	PredicateID       string                    `json:"predicate_id"`
	ProfileDigest     *string                   `json:"profile_digest,omitempty"`
	StartedAt         *string                   `json:"started_at,omitempty"`
	Subject           SymmetryEvidenceV1Subject `json:"subject"`
	SubjectHash       string                    `json:"subject_hash"`
	Commit            *string                   `json:"commit,omitempty"`
	ContentDigest     *string                   `json:"content_digest,omitempty"`
	Path              *string                   `json:"path,omitempty"`
	ResourceID        *string                   `json:"resource_id,omitempty"`
	Findings          []ReviewFinding           `json:"findings,omitempty"`
	ReviewTaskID      *string                   `json:"review_task_id,omitempty"`
	Verdict           *Verdict                  `json:"verdict,omitempty"`
	ExternalRef       *string                   `json:"external_ref,omitempty"`
	Note              *string                   `json:"note,omitempty"`
	ObservedAt        *string                   `json:"observed_at,omitempty"`
}

type ReviewFinding struct {
	Code     *string         `json:"code,omitempty"`
	Detail   *string         `json:"detail,omitempty"`
	Severity FindingSeverity `json:"severity"`
	Summary  string          `json:"summary"`
}

type OutputRef struct {
	Kind  OutputRefKind `json:"kind"`
	Value string        `json:"value"`
}

type SymmetryEvidenceV1Subject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type SourceRef struct {
	Kind             SymmetryEvidenceV1Kind `json:"kind"`
	Ref              string                 `json:"ref"`
	SubjectHash      string                 `json:"subject_hash"`
	ValidatorProfile *string                `json:"validator_profile,omitempty"`
	Commit           *string                `json:"commit,omitempty"`
	Path             *string                `json:"path,omitempty"`
	ResourceID       *string                `json:"resource_id,omitempty"`
	ReviewTaskID     *string                `json:"review_task_id,omitempty"`
	ExternalRef      *string                `json:"external_ref,omitempty"`
}

type SymmetryGoalCommandV1 struct {
	ExpectedRevision int64                              `json:"expected_revision"`
	ExpectedVersion  int64                              `json:"expected_version"`
	Kind             SymmetryGoalCommandV1Kind          `json:"kind"`
	MutationID       string                             `json:"mutation_id"`
	Payload          Payload                            `json:"payload"`
	SchemaVersion    SymmetryGoalCommandV1SchemaVersion `json:"schema_version"`
}

type Payload struct {
	ApprovedRevision        *int64                `json:"approved_revision,omitempty"`
	ModelProfile            *string               `json:"model_profile,omitempty"`
	RepositoryResourceID    *string               `json:"repository_resource_id,omitempty"`
	RequestedSessionID      *string               `json:"requested_session_id"`
	SessionMode             *SessionMode          `json:"session_mode,omitempty"`
	Subject                 *PurpleSubject        `json:"subject,omitempty"`
	Reason                  *string               `json:"reason,omitempty"`
	RevisionContract        *GoalRevisionContract `json:"revision_contract,omitempty"`
	DecisionID              *string               `json:"decision_id"`
	Proposal                *PayloadPlanProposal  `json:"proposal"`
	ProposalHash            *string               `json:"proposal_hash,omitempty"`
	Kind                    *PayloadKind          `json:"kind,omitempty"`
	SubjectHash             *string               `json:"subject_hash"`
	WorkItemID              *string               `json:"work_item_id"`
	Comment                 *string               `json:"comment"`
	ExpectedDecisionVersion *int64                `json:"expected_decision_version,omitempty"`
	OptionID                *string               `json:"option_id,omitempty"`
	Purpose                 *PayloadPurpose       `json:"purpose,omitempty"`
	ValidationOfTaskID      *string               `json:"validation_of_task_id"`
	HandoffSourceRunID      *string               `json:"handoff_source_run_id,omitempty"`
	DependsOnID             *string               `json:"depends_on_id,omitempty"`
	EvidenceIDS             []string              `json:"evidence_ids,omitempty"`
	IntegrationWorkItemID   *string               `json:"integration_work_item_id,omitempty"`
}

type PayloadPlanProposal struct {
	ExpectedRevision *int64                     `json:"expected_revision,omitempty"`
	GoalID           *string                    `json:"goal_id,omitempty"`
	Items            []PurplePlanItem           `json:"items,omitempty"`
	ProposalID       *string                    `json:"proposal_id,omitempty"`
	SchemaVersion    *PlanProposalSchemaVersion `json:"schema_version,omitempty"`
	DependsOnID      *string                    `json:"depends_on_id,omitempty"`
	Kind             *PlanProposalKind          `json:"kind,omitempty"`
}

type PurplePlanItem struct {
	Acceptance           ItemAcceptanceContract      `json:"acceptance"`
	Baseline             PurplePlanBaseline          `json:"baseline"`
	ChangeTarget         *PurpleProviderChangeTarget `json:"change_target"`
	DependsOnKeys        []string                    `json:"depends_on_keys"`
	Description          string                      `json:"description"`
	Integration          *bool                       `json:"integration,omitempty"`
	Key                  string                      `json:"key"`
	ModelProfile         string                      `json:"model_profile"`
	RepositoryResourceID string                      `json:"repository_resource_id"`
	Required             bool                        `json:"required"`
	Title                string                      `json:"title"`
}

type ItemAcceptanceContract struct {
	Description   string                  `json:"description"`
	Predicates    []FluffyPredicate       `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type FluffyPredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type PurplePlanBaseline struct {
	Kind    PlanBaselineKind `json:"kind"`
	Subject *PurpleSubject   `json:"subject,omitempty"`
	Key     *string          `json:"key,omitempty"`
}

type PurpleSubject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type PurpleProviderChangeTarget struct {
	Kind           ChangeTargetKind `json:"kind"`
	SourceBranch   *string          `json:"source_branch,omitempty"`
	TargetBranch   *string          `json:"target_branch,omitempty"`
	PullRequestURL *string          `json:"pull_request_url,omitempty"`
}

type GoalRevisionContract struct {
	AcceptanceContract ItemAcceptanceContract          `json:"acceptance_contract"`
	AuthorityPolicy    RevisionContractAuthorityPolicy `json:"authority_policy"`
	ContextManifest    RevisionContractContextManifest `json:"context_manifest"`
	ExecutionPolicy    RevisionContractExecutionPolicy `json:"execution_policy"`
	NonGoals           []string                        `json:"non_goals"`
	Objective          string                          `json:"objective"`
}

type RevisionContractAuthorityPolicy struct {
	AllowedActions                 []string `json:"allowed_actions"`
	OperatorRequiredForCompletion  bool     `json:"operator_required_for_completion"`
	OperatorRequiredForScopeChange bool     `json:"operator_required_for_scope_change"`
	PublicationAllowed             bool     `json:"publication_allowed"`
}

type RevisionContractContextManifest struct {
	ByteBudget            int64    `json:"byte_budget"`
	IncludeAdvisoryRecall bool     `json:"include_advisory_recall"`
	RequiredSourceKinds   []string `json:"required_source_kinds"`
}

type RevisionContractExecutionPolicy struct {
	AllowedActions          []string        `json:"allowed_actions"`
	AllowedModelProfiles    []string        `json:"allowed_model_profiles"`
	AllowedResourceIDS      []string        `json:"allowed_resource_ids"`
	AllowedRuntimeIDS       []string        `json:"allowed_runtime_ids"`
	AutomaticExecution      bool            `json:"automatic_execution"`
	BudgetLimitMicrousd     *string         `json:"budget_limit_microusd"`
	BudgetMode              BudgetMode      `json:"budget_mode"`
	FinalAcceptance         FinalAcceptance `json:"final_acceptance"`
	HardCostLimitRequired   bool            `json:"hard_cost_limit_required"`
	MaxParallelTasks        int64           `json:"max_parallel_tasks"`
	MaxRunAttemptsPerTask   int64           `json:"max_run_attempts_per_task"`
	MaxTaskAdmissions       int64           `json:"max_task_admissions"`
	PerRunCostLimitMicrousd *string         `json:"per_run_cost_limit_microusd"`
}

type SymmetryGoalCreateV1 struct {
	InitialRevision InitialGoalRevisionContract       `json:"initial_revision"`
	MutationID      string                            `json:"mutation_id"`
	SchemaVersion   SymmetryGoalCreateV1SchemaVersion `json:"schema_version"`
	Title           string                            `json:"title"`
}

type InitialGoalRevisionContract struct {
	AcceptanceContract InitialRevisionAcceptanceContract `json:"acceptance_contract"`
	AuthorityPolicy    InitialRevisionAuthorityPolicy    `json:"authority_policy"`
	ContextManifest    InitialRevisionContextManifest    `json:"context_manifest"`
	ExecutionPolicy    InitialRevisionExecutionPolicy    `json:"execution_policy"`
	NonGoals           []string                          `json:"non_goals"`
	Objective          string                            `json:"objective"`
	Reason             string                            `json:"reason"`
}

type InitialRevisionAcceptanceContract struct {
	Description   string                  `json:"description"`
	Predicates    []TentacledPredicate    `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type TentacledPredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type InitialRevisionAuthorityPolicy struct {
	AllowedActions                 []string `json:"allowed_actions"`
	OperatorRequiredForCompletion  bool     `json:"operator_required_for_completion"`
	OperatorRequiredForScopeChange bool     `json:"operator_required_for_scope_change"`
	PublicationAllowed             bool     `json:"publication_allowed"`
}

type InitialRevisionContextManifest struct {
	ByteBudget            int64    `json:"byte_budget"`
	IncludeAdvisoryRecall bool     `json:"include_advisory_recall"`
	RequiredSourceKinds   []string `json:"required_source_kinds"`
}

type InitialRevisionExecutionPolicy struct {
	AllowedActions          []string        `json:"allowed_actions"`
	AllowedModelProfiles    []string        `json:"allowed_model_profiles"`
	AllowedResourceIDS      []string        `json:"allowed_resource_ids"`
	AllowedRuntimeIDS       []string        `json:"allowed_runtime_ids"`
	AutomaticExecution      bool            `json:"automatic_execution"`
	BudgetLimitMicrousd     *string         `json:"budget_limit_microusd"`
	BudgetMode              BudgetMode      `json:"budget_mode"`
	FinalAcceptance         FinalAcceptance `json:"final_acceptance"`
	HardCostLimitRequired   bool            `json:"hard_cost_limit_required"`
	MaxParallelTasks        int64           `json:"max_parallel_tasks"`
	MaxRunAttemptsPerTask   int64           `json:"max_run_attempts_per_task"`
	MaxTaskAdmissions       int64           `json:"max_task_admissions"`
	PerRunCostLimitMicrousd *string         `json:"per_run_cost_limit_microusd"`
}

type SymmetryGoalRevisionV1 struct {
	AcceptanceContract SymmetryGoalRevisionV1AcceptanceContract `json:"acceptance_contract"`
	ActorRef           string                                   `json:"actor_ref"`
	AuthorityPolicy    SymmetryGoalRevisionV1AuthorityPolicy    `json:"authority_policy"`
	ContextManifest    SymmetryGoalRevisionV1ContextManifest    `json:"context_manifest"`
	ExecutionPolicy    SymmetryGoalRevisionV1ExecutionPolicy    `json:"execution_policy"`
	GoalID             string                                   `json:"goal_id"`
	InsertedAt         string                                   `json:"inserted_at"`
	NonGoals           []string                                 `json:"non_goals"`
	Objective          string                                   `json:"objective"`
	Reason             string                                   `json:"reason"`
	Revision           int64                                    `json:"revision"`
	SchemaVersion      SymmetryGoalRevisionV1SchemaVersion      `json:"schema_version"`
}

type SymmetryGoalRevisionV1AcceptanceContract struct {
	Description   string                  `json:"description"`
	Predicates    []StickyPredicate       `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type StickyPredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type SymmetryGoalRevisionV1AuthorityPolicy struct {
	AllowedActions                 []string `json:"allowed_actions"`
	OperatorRequiredForCompletion  bool     `json:"operator_required_for_completion"`
	OperatorRequiredForScopeChange bool     `json:"operator_required_for_scope_change"`
	PublicationAllowed             bool     `json:"publication_allowed"`
}

type SymmetryGoalRevisionV1ContextManifest struct {
	ByteBudget            int64    `json:"byte_budget"`
	IncludeAdvisoryRecall bool     `json:"include_advisory_recall"`
	RequiredSourceKinds   []string `json:"required_source_kinds"`
}

type SymmetryGoalRevisionV1ExecutionPolicy struct {
	AllowedActions          []string        `json:"allowed_actions"`
	AllowedModelProfiles    []string        `json:"allowed_model_profiles"`
	AllowedResourceIDS      []string        `json:"allowed_resource_ids"`
	AllowedRuntimeIDS       []string        `json:"allowed_runtime_ids"`
	AutomaticExecution      bool            `json:"automatic_execution"`
	BudgetLimitMicrousd     *string         `json:"budget_limit_microusd"`
	BudgetMode              BudgetMode      `json:"budget_mode"`
	FinalAcceptance         FinalAcceptance `json:"final_acceptance"`
	HardCostLimitRequired   bool            `json:"hard_cost_limit_required"`
	MaxParallelTasks        int64           `json:"max_parallel_tasks"`
	MaxRunAttemptsPerTask   int64           `json:"max_run_attempts_per_task"`
	MaxTaskAdmissions       int64           `json:"max_task_admissions"`
	PerRunCostLimitMicrousd *string         `json:"per_run_cost_limit_microusd"`
}

type SymmetryPlanProposalV1 struct {
	ExpectedRevision int64                        `json:"expected_revision"`
	GoalID           string                       `json:"goal_id"`
	Items            []SymmetryPlanProposalV1Item `json:"items"`
	ProposalID       string                       `json:"proposal_id"`
	SchemaVersion    PlanProposalSchemaVersion    `json:"schema_version"`
}

type SymmetryPlanProposalV1Item struct {
	Acceptance           PurpleAcceptanceContract    `json:"acceptance"`
	Baseline             FluffyPlanBaseline          `json:"baseline"`
	ChangeTarget         *FluffyProviderChangeTarget `json:"change_target"`
	DependsOnKeys        []string                    `json:"depends_on_keys"`
	Description          string                      `json:"description"`
	Integration          *bool                       `json:"integration,omitempty"`
	Key                  string                      `json:"key"`
	ModelProfile         string                      `json:"model_profile"`
	RepositoryResourceID string                      `json:"repository_resource_id"`
	Required             bool                        `json:"required"`
	Title                string                      `json:"title"`
}

type PurpleAcceptanceContract struct {
	Description   string                  `json:"description"`
	Predicates    []IndigoPredicate       `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type IndigoPredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type FluffyPlanBaseline struct {
	Kind    PlanBaselineKind `json:"kind"`
	Subject *FluffySubject   `json:"subject,omitempty"`
	Key     *string          `json:"key,omitempty"`
}

type FluffySubject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type FluffyProviderChangeTarget struct {
	Kind           ChangeTargetKind `json:"kind"`
	SourceBranch   *string          `json:"source_branch,omitempty"`
	TargetBranch   *string          `json:"target_branch,omitempty"`
	PullRequestURL *string          `json:"pull_request_url,omitempty"`
}

type SymmetryTaskResultV1 struct {
	Blocker            *Blocker                          `json:"blocker"`
	Diagnostics        []Diagnostic                      `json:"diagnostics"`
	EvidenceRefs       []string                          `json:"evidence_refs"`
	Kind               SymmetryTaskResultV1Kind          `json:"kind"`
	Proposal           *SymmetryTaskResultV1PlanProposal `json:"proposal"`
	ProposedNextAction *ProposedNextActionClass          `json:"proposed_next_action"`
	Reason             *Reason                           `json:"reason"`
	ResultID           string                            `json:"result_id"`
	SchemaVersion      SymmetryTaskResultV1SchemaVersion `json:"schema_version"`
	Subject            SymmetryTaskResultV1Subject       `json:"subject"`
	SubjectHash        string                            `json:"subject_hash"`
	Summary            string                            `json:"summary"`
}

type Blocker struct {
	DecisionID  *string     `json:"decision_id,omitempty"`
	Kind        BlockerKind `json:"kind"`
	ExternalRef *string     `json:"external_ref,omitempty"`
	NextCheckAt *string     `json:"next_check_at,omitempty"`
	ResourceID  *string     `json:"resource_id,omitempty"`
	WorkItemIDS []string    `json:"work_item_ids,omitempty"`
	Code        *string     `json:"code,omitempty"`
	Detail      *string     `json:"detail,omitempty"`
}

type Diagnostic struct {
	Code     string              `json:"code"`
	Message  string              `json:"message"`
	Severity *DiagnosticSeverity `json:"severity,omitempty"`
}

type SymmetryTaskResultV1PlanProposal struct {
	ExpectedRevision int64                     `json:"expected_revision"`
	GoalID           string                    `json:"goal_id"`
	Items            []FluffyPlanItem          `json:"items"`
	ProposalID       string                    `json:"proposal_id"`
	SchemaVersion    PlanProposalSchemaVersion `json:"schema_version"`
}

type FluffyPlanItem struct {
	Acceptance           FluffyAcceptanceContract       `json:"acceptance"`
	Baseline             TentacledPlanBaseline          `json:"baseline"`
	ChangeTarget         *TentacledProviderChangeTarget `json:"change_target"`
	DependsOnKeys        []string                       `json:"depends_on_keys"`
	Description          string                         `json:"description"`
	Integration          *bool                          `json:"integration,omitempty"`
	Key                  string                         `json:"key"`
	ModelProfile         string                         `json:"model_profile"`
	RepositoryResourceID string                         `json:"repository_resource_id"`
	Required             bool                           `json:"required"`
	Title                string                         `json:"title"`
}

type FluffyAcceptanceContract struct {
	Description   string                  `json:"description"`
	Predicates    []IndecentPredicate     `json:"predicates"`
	SchemaVersion AcceptanceSchemaVersion `json:"schema_version"`
}

type IndecentPredicate struct {
	ID               string        `json:"id"`
	Kind             PredicateKind `json:"kind"`
	ValidatorProfile *string       `json:"validator_profile,omitempty"`
	Path             *string       `json:"path,omitempty"`
	ResourceID       *string       `json:"resource_id,omitempty"`
	ReviewerProfile  *string       `json:"reviewer_profile,omitempty"`
}

type TentacledPlanBaseline struct {
	Kind    PlanBaselineKind             `json:"kind"`
	Subject *SymmetryTaskResultV1Subject `json:"subject,omitempty"`
	Key     *string                      `json:"key,omitempty"`
}

type SymmetryTaskResultV1Subject struct {
	Commit     string `json:"commit"`
	ResourceID string `json:"resource_id"`
	TreeDigest string `json:"tree_digest"`
}

type TentacledProviderChangeTarget struct {
	Kind           ChangeTargetKind `json:"kind"`
	SourceBranch   *string          `json:"source_branch,omitempty"`
	TargetBranch   *string          `json:"target_branch,omitempty"`
	PullRequestURL *string          `json:"pull_request_url,omitempty"`
}

type ProposedNextActionClass struct {
	Kind            NextActionKind             `json:"kind"`
	ProducingTaskID *string                    `json:"producing_task_id,omitempty"`
	Reason          *string                    `json:"reason,omitempty"`
	WorkItemID      *string                    `json:"work_item_id,omitempty"`
	ExternalRef     *string                    `json:"external_ref,omitempty"`
	ResourceID      *string                    `json:"resource_id,omitempty"`
	Blocker         *ProposedNextActionBlocker `json:"blocker,omitempty"`
}

type ProposedNextActionBlocker struct {
	DecisionID  *string     `json:"decision_id,omitempty"`
	Kind        BlockerKind `json:"kind"`
	ExternalRef *string     `json:"external_ref,omitempty"`
	NextCheckAt *string     `json:"next_check_at,omitempty"`
	ResourceID  *string     `json:"resource_id,omitempty"`
	WorkItemIDS []string    `json:"work_item_ids,omitempty"`
	Code        *string     `json:"code,omitempty"`
	Detail      *string     `json:"detail,omitempty"`
}

type SymmetryUsageV1 struct {
	CachedInputTokens *int64                       `json:"cached_input_tokens"`
	CostBasis         Usage                        `json:"cost_basis"`
	CostMicrousd      *string                      `json:"cost_microusd"`
	InputTokens       *int64                       `json:"input_tokens"`
	Model             string                       `json:"model"`
	ObservedAt        string                       `json:"observed_at"`
	OutputTokens      *int64                       `json:"output_tokens"`
	PriceVersion      *string                      `json:"price_version"`
	Provider          string                       `json:"provider"`
	RunID             string                       `json:"run_id"`
	SchemaVersion     SymmetryUsageV1SchemaVersion `json:"schema_version"`
	SupersedesID      *string                      `json:"supersedes_id"`
	UsageID           string                       `json:"usage_id"`
	UsageKey          string                       `json:"usage_key"`
}

type Guidance string

const (
	GuidanceUnsupported Guidance = "unsupported"
	NativeSteer         Guidance = "native_steer"
	NextTurn            Guidance = "next_turn"
)

type PauseEnum string

const (
	PauseUnsupported PauseEnum = "unsupported"
	SafeBoundary     PauseEnum = "safe_boundary"
)

type Usage string

const (
	Estimated    Usage = "estimated"
	Reported     Usage = "reported"
	UsageUnknown Usage = "unknown"
)

type SymmetryAdmissionV1Purpose string

const (
	PurpleImplement SymmetryAdmissionV1Purpose = "implement"
	PurpleValidate  SymmetryAdmissionV1Purpose = "validate"
)

type SymmetryAdmissionV1SchemaVersion string

const (
	SchemaVersionSymmetryAdmissionV1 SymmetryAdmissionV1SchemaVersion = "symmetry.admission.v1"
)

type SessionMode string

const (
	Fresh             SessionMode = "fresh"
	Handoff           SessionMode = "handoff"
	SessionModeResume SessionMode = "resume"
)

type ContentKind string

const (
	Evidence ContentKind = "evidence"
	Excerpt  ContentKind = "excerpt"
	Path     ContentKind = "path"
	Pointer  ContentKind = "pointer"
)

type Trust string

const (
	Advisory            Trust = "advisory"
	RepositoryUntrusted Trust = "repository_untrusted"
	TrustedPolicy       Trust = "trusted_policy"
	ValidatedEvidence   Trust = "validated_evidence"
)

type State string

const (
	Open       State = "open"
	Resolved   State = "resolved"
	Superseded State = "superseded"
)

type BlockerKind string

const (
	Decision         BlockerKind = "decision"
	Environment      BlockerKind = "environment"
	External         BlockerKind = "external"
	PurpleDependency BlockerKind = "dependency"
)

type NextActionKind string

const (
	KindObserve  NextActionKind = "observe"
	KindValidate NextActionKind = "validate"
	Repair       NextActionKind = "repair"
	Replan       NextActionKind = "replan"
	Wait         NextActionKind = "wait"
)

type SymmetryContextSnapshotV1SchemaVersion string

const (
	SchemaVersionSymmetryContextSnapshotV1 SymmetryContextSnapshotV1SchemaVersion = "symmetry.context_snapshot.v1"
)

type Verdict string

const (
	NotApplicable  Verdict = "not_applicable"
	Passed         Verdict = "passed"
	VerdictFailed  Verdict = "failed"
	VerdictUnknown Verdict = "unknown"
)

type PredicateKind string

const (
	OperatorAcceptance PredicateKind = "operator_acceptance"
	PurpleArtifact     PredicateKind = "artifact"
	PurpleCheck        PredicateKind = "check"
	PurpleReview       PredicateKind = "review"
)

type AcceptanceSchemaVersion string

const (
	SymmetryAcceptanceV1 AcceptanceSchemaVersion = "symmetry.acceptance.v1"
)

type ChangeTargetKind string

const (
	Branches    ChangeTargetKind = "branches"
	PullRequest ChangeTargetKind = "pull_request"
)

type WorkContractPurpose string

const (
	FluffyImplement WorkContractPurpose = "implement"
	FluffyValidate  WorkContractPurpose = "validate"
	PurpleChat      WorkContractPurpose = "chat"
	PurpleObserve   WorkContractPurpose = "observe"
	PurposePlan     WorkContractPurpose = "plan"
)

type ValidationBindingKind string

const (
	FluffyCheck  ValidationBindingKind = "check"
	FluffyReview ValidationBindingKind = "review"
)

type SymmetryDecisionV1Kind string

const (
	Budget           SymmetryDecisionV1Kind = "budget"
	ExternalAction   SymmetryDecisionV1Kind = "external_action"
	PurpleCompletion SymmetryDecisionV1Kind = "completion"
	PurplePlan       SymmetryDecisionV1Kind = "plan"
	PurpleScope      SymmetryDecisionV1Kind = "scope"
	TentacledReview  SymmetryDecisionV1Kind = "review"
)

type SymmetryDecisionV1SchemaVersion string

const (
	SchemaVersionSymmetryDecisionV1 SymmetryDecisionV1SchemaVersion = "symmetry.decision.v1"
)

type SymmetryEvidenceV1Kind string

const (
	FluffyArtifact SymmetryEvidenceV1Kind = "artifact"
	Observation    SymmetryEvidenceV1Kind = "observation"
	StickyReview   SymmetryEvidenceV1Kind = "review"
	TentacledCheck SymmetryEvidenceV1Kind = "check"
)

type FindingSeverity string

const (
	Critical   FindingSeverity = "critical"
	High       FindingSeverity = "high"
	Low        FindingSeverity = "low"
	Medium     FindingSeverity = "medium"
	PurpleInfo FindingSeverity = "info"
)

type OutputRefKind string

const (
	Inline            OutputRefKind = "inline"
	TentacledArtifact OutputRefKind = "artifact"
)

type SymmetryEvidenceV1SchemaVersion string

const (
	SchemaVersionSymmetryEvidenceV1 SymmetryEvidenceV1SchemaVersion = "symmetry.evidence.v1"
)

type SymmetryGoalCommandV1Kind string

const (
	AcceptPlan             SymmetryGoalCommandV1Kind = "accept_plan"
	Achieve                SymmetryGoalCommandV1Kind = "achieve"
	Activate               SymmetryGoalCommandV1Kind = "activate"
	AdmitTask              SymmetryGoalCommandV1Kind = "admit_task"
	Amend                  SymmetryGoalCommandV1Kind = "amend"
	Cancel                 SymmetryGoalCommandV1Kind = "cancel"
	KindResume             SymmetryGoalCommandV1Kind = "resume"
	Pause                  SymmetryGoalCommandV1Kind = "pause"
	PurpleAddDependency    SymmetryGoalCommandV1Kind = "add_dependency"
	PurpleRemoveDependency SymmetryGoalCommandV1Kind = "remove_dependency"
	RequestDecision        SymmetryGoalCommandV1Kind = "request_decision"
	RequestPlan            SymmetryGoalCommandV1Kind = "request_plan"
	ResolveDecision        SymmetryGoalCommandV1Kind = "resolve_decision"
)

type PayloadKind string

const (
	FluffyCompletion PayloadKind = "completion"
	FluffyPlan       PayloadKind = "plan"
	FluffyScope      PayloadKind = "scope"
	IndigoReview     PayloadKind = "review"
)

type PlanBaselineKind string

const (
	FluffyDependency PlanBaselineKind = "dependency"
	Subject          PlanBaselineKind = "subject"
)

type PlanProposalKind string

const (
	FluffyAddDependency    PlanProposalKind = "add_dependency"
	FluffyRemoveDependency PlanProposalKind = "remove_dependency"
)

type PlanProposalSchemaVersion string

const (
	SymmetryPlanV1 PlanProposalSchemaVersion = "symmetry.plan.v1"
)

type PayloadPurpose string

const (
	FluffyChat         PayloadPurpose = "chat"
	FluffyObserve      PayloadPurpose = "observe"
	TentacledImplement PayloadPurpose = "implement"
	TentacledValidate  PayloadPurpose = "validate"
)

type BudgetMode string

const (
	Soft   BudgetMode = "soft"
	Strict BudgetMode = "strict"
)

type FinalAcceptance string

const (
	Deterministic FinalAcceptance = "deterministic"
	Operator      FinalAcceptance = "operator"
)

type SymmetryGoalCommandV1SchemaVersion string

const (
	SchemaVersionSymmetryGoalCommandV1 SymmetryGoalCommandV1SchemaVersion = "symmetry.goal_command.v1"
)

type SymmetryGoalCreateV1SchemaVersion string

const (
	SchemaVersionSymmetryGoalCreateV1 SymmetryGoalCreateV1SchemaVersion = "symmetry.goal_create.v1"
)

type SymmetryGoalRevisionV1SchemaVersion string

const (
	SchemaVersionSymmetryGoalRevisionV1 SymmetryGoalRevisionV1SchemaVersion = "symmetry.goal_revision.v1"
)

type DiagnosticSeverity string

const (
	Error      DiagnosticSeverity = "error"
	FluffyInfo DiagnosticSeverity = "info"
	Warning    DiagnosticSeverity = "warning"
)

type SymmetryTaskResultV1Kind string

const (
	Blocked             SymmetryTaskResultV1Kind = "blocked"
	CandidateCompletion SymmetryTaskResultV1Kind = "candidate_completion"
	KindFailed          SymmetryTaskResultV1Kind = "failed"
	PlanProposed        SymmetryTaskResultV1Kind = "plan_proposed"
	Progress            SymmetryTaskResultV1Kind = "progress"
	RepairRequired      SymmetryTaskResultV1Kind = "repair_required"
	ReplanRequired      SymmetryTaskResultV1Kind = "replan_required"
)

type Reason string

const (
	Auth               Reason = "auth"
	Cancelled          Reason = "cancelled"
	ContextOverflow    Reason = "context_overflow"
	HandoffUnsupported Reason = "handoff_unsupported"
	MissingResult      Reason = "missing_result"
	Network            Reason = "network"
	ProcessFailure     Reason = "process_failure"
	Quota              Reason = "quota"
	RateLimit          Reason = "rate_limit"
	ResumeRejected     Reason = "resume_rejected"
	UnknownOutcome     Reason = "unknown_outcome"
	UnsupportedVersion Reason = "unsupported_version"
)

type SymmetryTaskResultV1SchemaVersion string

const (
	SchemaVersionSymmetryTaskResultV1 SymmetryTaskResultV1SchemaVersion = "symmetry.task_result.v1"
)

type SymmetryUsageV1SchemaVersion string

const (
	SchemaVersionSymmetryUsageV1 SymmetryUsageV1SchemaVersion = "symmetry.usage.v1"
)
