defmodule SymmetryControlWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :symmetry_control

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_symmetry_control_key",
    signing_salt: "AsyeG8tI",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:symmetry_control, :portal_session_secure, false)
  ]

  socket "/socket", SymmetryControlWeb.UserSocket,
    websocket: [connect_info: [:x_headers]],
    longpoll: false

  plug Plug.Static,
    at: "/assets",
    from: {:symmetry_control, "priv/portal_assets"},
    gzip: false,
    only: ~w(portal.css portal.js)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :symmetry_control,
    gzip: not code_reloading?,
    only: SymmetryControlWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :symmetry_control
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SymmetryControlWeb.Router
end
